### ISSUE TITLE
Pull requestって

### ISSUE THREAD

**Issue by chottokun** [chottokun/Rec-adio#10]
出して良いものかしら・・・

**Comment by sun-yryr** [comment]
助かりますw

**Comment by chottokun** [comment]
良くも分からず、Pull request。commitのコメントは眠くてtypoいっぱいあるママだ。
git rebase -i で全差分を1 commitにまとめてからとか、書いてあったりもする。だが、README.mdなんかはマージしないだろうし。そのあたりの整合性をgithubではどう取り込むのだろうか。

**Comment by chottokun** [comment]
やらかしたかも。Push request専用のブランチ作ってあげるのがいいのか。分からないぞ（笑）
